---
- block:
  - name: install sentinel script
    copy:
      src: sentinel
      dest: "/usr/local/bin/sentinel"
      mode: 0775
    tags:
      - sentinel

  - name: install sentinel.service
    template:
      src: sentinel.service.j2
      dest: "{{ systemd_dir }}/sentinel.service"
    tags:
      - sentinel

  - name: install sentinel systemd unit
    copy:
      src: sentinel.timer
      dest: "{{ systemd_dir }}/sentinel.timer"
    notify:
      - reload systemd
    tags:
      - sentinel

  - name: enable sentinel units
    service:
      name: "{{item}}"
      enabled: yes
    with_items:
      - sentinel.service
      - sentinel.timer
    tags:
      - sentinel

  - name: start the timer unit
    service:
      name: sentinel.timer
      state: restarted
    tags:
      - sentinel

  become: true
  become_user: root
